---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: test
  labels:
    name: app
spec:
  type: ClusterIP
  selector:
    name: app
  ports:
  - name: http
    port: 80
    targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: test
  labels:
    name: app
spec:
  containers:
  - name: app
    image: nginx:1.25.2
    ports:
    - containerPort: 80

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app
  namespace: test
spec:
  podSelector:
    matchLabels:
      name: app
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
      - podSelector:
          matchLabels:
            name: db
      ports:
        - protocol: TCP
          port: 80
    # dns udp
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
      ports:
      - protocol: UDP
        port: 53
