---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: test
  labels:
    name: db
spec:
  type: ClusterIP
  selector:
    name: db
  ports:
  - name: http
    port: 80
    targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: test
  labels:
    name: db
spec:
  containers:
  - name: db
    image: nginx:1.25.2
    ports:
    - containerPort: 80

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db
  namespace: test
spec:
  podSelector:
    matchLabels:
      name: db
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # app
    - from:
      - podSelector:
          matchLabels:
            name: app
      ports:
        - protocol: TCP
          port: 80
  egress:
    # dns udp
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
      ports:
      - protocol: UDP
        port: 53
