---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: required-labels
spec:
  # enforcementAction: warn
  match:
    namespaces: ["dev"]
    kinds:
      - apiGroups: [""]
        kinds:
        - ConfigMap
        - Pod
        - Secret
      - apiGroups: ["apps"]
        kinds:
        - Deployment
        - ReplicaSet
  parameters:
    labels:
      - key: app.kubernetes.io/name
