apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gatekeeper-system
resources:
  - constraint-template-disallowed-tags.yml
  - constraint-template-required-labels.yml
  - constraints-disallowed-tags.yml
  - constraints-required-labels.yml
