---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: production
spec:
  version: v2.43.1
  serviceAccountName: prometheus
  podMonitorSelector:
    matchLabels:
      prometheus.io/scrape: "true"
  podMonitorNamespaceSelector:
    matchLabels:
      prometheus.io/scrape: "true"
  serviceMonitorSelector:
    matchLabels:
      prometheus.io/scrape: "true"
  serviceMonitorNamespaceSelector:
    matchLabels:
      prometheus.io/scrape: "true"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 2Gi
  replicas: 1
  logLevel: info
  logFormat: logfmt
  retention: 6h
  scrapeInterval: 15s
  securityContext:
    fsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  containers:
    - name: prometheus
