apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gatekeeper-system
resources:
  - bundle.yml

patches:
  - target:
      kind: Namespace
    patch: |
      - op: add
        path: /metadata/labels/prometheus.io~1scrape
        value: "true"
