---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-not-valid-labels
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.2
        ports:
        - containerPort: 80
