---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-not-valid-image-tag
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
